# Generated by Django 3.1.5 on 2021-01-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=10)),
                ('profile_image', models.ImageField(default='media/default_image.jpeg', upload_to='')),
            ],
        ),
    ]
