# Generated by Django 3.1.5 on 2021-01-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwtauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
