# Generated by Django 3.1.5 on 2021-01-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwtauth', '0002_auto_20210119_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='username',
        ),
    ]
